name: Automerge Release PRs

on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, format('autorelease{0} pending', ':'))
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}

      - run: gh pr merge -R "${{ github.repository }}" --rebase --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
