name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Build release artifact
        run: npm install && npm run release

      - name: Upload Stream Deck plugin artifact
        if: ${{ steps.release.outputs.upload_url }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: release/com.voltzmakes.dark-mode-toggle.streamDeckPlugin
          asset_name: com.voltzmakes.dark-mode-toggle.streamDeckPlugin
          asset_content_type: application/octet-stream
